title: Sergio Kisliy
email: your-email@example.com
description: >-
  My CV
baseurl: ""
url: "https://skislits.github.io"
github_username:  skislits

social:
  name: Sergio Kisliy

# Build settings
theme: minima

collections:
 cv:
    output: true

plugins:
  - jekyll-feed
  - jekyll-pdf


# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

